name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: execute py script # run the run.py to get the latest data
        run: |
          python generate_files.py
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/data